apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 439667737553.dkr.ecr.us-east-1.amazonaws.com/pedidos-repo:latest
          ports:
            - containerPort: 8080  # Corrigido para 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=db-service;Port=3306;Database=app_db;User=app_user;Password=app_password;"
      imagePullSecrets:
       - name: ecr-secret
