name: Code Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  validador-cobertura-testes-70:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.coverage-check.outputs.should_deploy }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install ReportGenerator tool
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Convert to HTML report
        run: |
          reportgenerator \
            -reports:"**/coverage.cobertura.xml" \
            -targetdir:"coverlet/reports" \
            -reporttypes:Html

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Validate code coverage
        id: coverage-check
        shell: bash
        run: |
          minCoverage=70
          coverageReportPath="coverlet/reports/Cobertura.xml"

          if [ ! -f "$coverageReportPath" ]; then
            echo "Arquivo de cobertura não encontrado em $coverageReportPath"
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            exit 1
          fi

          coveragePercentage=$(xmllint --xpath "string(//coverage/@line-rate)" "$coverageReportPath")
          coveragePercentagePerc=$(echo "$coveragePercentage * 100" | bc -l | xargs printf "%.2f")

          if (( $(echo "$coveragePercentagePerc < $minCoverage" | bc -l) )); then
            echo "❌ Cobertura de código $coveragePercentagePerc% está abaixo de $minCoverage%"
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "✅ Cobertura de código $coveragePercentagePerc% está acima de $minCoverage%"
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          fi

  publicar-relatorio-coverage:
    needs: validador-cobertura-testes-70
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Copiar relatório para gh-pages
        run: |
          git fetch
          git switch --orphan gh-pages
          git rm -rf .
          cp -r coverlet/reports/* .
          touch .nojekyll
          git add .
          git commit -m "Atualiza relatório de cobertura"
          git push --force origin gh-pages
