name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Run a container
        run: |
          docker run --rm hello-world